In [1]:
from Modules.evaluation import join_gt_and_our_dataframes, get_semantic_similarity_eval, get_distribution_metrics
from Modules.plotting_charts import plot_results

In [2]:
""" Constants """

GT_DF_PATH = 'Datasets/jsonllm/balanced_datasets_merge.parquet'
LX_DF_PATH = 'Datasets/lx_jsonllm/lx_jsonllm.parquet'

# Loading Datasets
MERGED_DF = join_gt_and_our_dataframes(GT_DF_PATH, LX_DF_PATH)
small_testing = MERGED_DF[:100].copy()  # For quick testing purposes
small_testing

,unique_id,dataset,text,gt_json_answer,lx_json_answer
0,1534,mave,"""A searing, thrilling, intelligent and often b...","{""Type"": ""fiction""}","{""author"": ""John Connolly"", ""title"": ""The Blac..."
1,1764,mave,"""Actually, this IS my first rodeo"" Outfit your...","{""Style"": ""bodysuit""}","{""brand"": null, ""category"": ""roupa de equitaçã..."
2,3416,mave,"""From a darkly humorous tale of the power of w...","{""Type"": ""fiction""}","{""author"": ""Jerry Friesner, Timothy Zahn, and ..."
4,4270,mave,"""In a debut novel that will appeal to fans of ...","{""Fiction Form"": ""novel""}","{""genre"": ""history"", ""author"": ""McDonald""}"
5,4361,mave,"""In this uproarious new memoir, a New York-rai...","{""Fiction Form"": ""short-story""}","{""author"": ""Keenan"", ""category"": ""Memoir"", ""ge..."
...,...,...,...,...,...
99,42556,ae-110k,1000M Super Strong 4 Strand 1000M Premium PE B...,"{""Material"": ""PE""}","{""brand"": null, ""category"": ""fishing line"", ""m..."
100,42597,ae-110k,1000W 48V 21AH Rear Rack Battery 48 volt batte...,"{""Capacity"": ""21AH"", ""BMS"": ""30A""}","{""brand"": null, ""category"": ""bateria de carro""..."
101,42808,mave,100W 120V Clear Single Ended Halogen Light Bulb,"{""Type"": ""Halogen""}","{""wattage"": ""100W"", ""voltage"": ""120V"", ""type"":..."
102,42843,ae-110k,100X Mini Microscope With LED Pen Mini Portabl...,"{""Model Number"": ""100X Mini Microscope With LE...","{""brand"": null, ""category"": ""microscopes"", ""co..."
103,43006,ae-110k,100pcs/pack Camping Nail Night Vision Luminous...,"{""Accessory Type"": ""Tent Nail""}","{""quantity"": ""100pcs/pack"", ""category"": ""Tents..."

In [3]:
""" Computing Similarities """

# new_run_full_evaluation(merged_df)
small_testing = get_semantic_similarity_eval(small_testing)
small_testing

Embeddings and similarities already exist. Loading from disk...

,unique_id,dataset,text,gt_json_answer,lx_json_answer,text_vs_gt_similarity_score,text_vs_lx_similarity_score,gt_vs_lx_similarity_score
0,1534,mave,"""A searing, thrilling, intelligent and often b...","{""Type"": ""fiction""}","{""author"": ""John Connolly"", ""title"": ""The Blac...",0.552914,0.891223,0.669711
1,1764,mave,"""Actually, this IS my first rodeo"" Outfit your...","{""Style"": ""bodysuit""}","{""brand"": null, ""category"": ""roupa de equitaçã...",0.632537,0.656277,0.699425
2,3416,mave,"""From a darkly humorous tale of the power of w...","{""Type"": ""fiction""}","{""author"": ""Jerry Friesner, Timothy Zahn, and ...",0.570173,0.825061,0.678833
4,4270,mave,"""In a debut novel that will appeal to fans of ...","{""Fiction Form"": ""novel""}","{""genre"": ""history"", ""author"": ""McDonald""}",0.535603,0.720675,0.605515
5,4361,mave,"""In this uproarious new memoir, a New York-rai...","{""Fiction Form"": ""short-story""}","{""author"": ""Keenan"", ""category"": ""Memoir"", ""ge...",0.474370,0.745946,0.638407
...,...,...,...,...,...,...,...,...
99,42556,ae-110k,1000M Super Strong 4 Strand 1000M Premium PE B...,"{""Material"": ""PE""}","{""brand"": null, ""category"": ""fishing line"", ""m...",0.548679,0.821067,0.688716
100,42597,ae-110k,1000W 48V 21AH Rear Rack Battery 48 volt batte...,"{""Capacity"": ""21AH"", ""BMS"": ""30A""}","{""brand"": null, ""category"": ""bateria de carro""...",0.651859,0.738129,0.718441
101,42808,mave,100W 120V Clear Single Ended Halogen Light Bulb,"{""Type"": ""Halogen""}","{""wattage"": ""100W"", ""voltage"": ""120V"", ""type"":...",0.699050,0.870392,0.846616
102,42843,ae-110k,100X Mini Microscope With LED Pen Mini Portabl...,"{""Model Number"": ""100X Mini Microscope With LE...","{""brand"": null, ""category"": ""microscopes"", ""co...",0.841067,0.732397,0.879199
103,43006,ae-110k,100pcs/pack Camping Nail Night Vision Luminous...,"{""Accessory Type"": ""Tent Nail""}","{""quantity"": ""100pcs/pack"", ""category"": ""Tents...",0.790756,0.731913,0.703572

In [6]:
""" Printing Metrics """

title = 'Similarity: Text VS GT'
metrics = get_distribution_metrics(
    small_testing['text_vs_gt_similarity_score'], title=title)
# print(metrics)

title = 'Similarity: Text VS LX'
metrics = get_distribution_metrics(
    small_testing['text_vs_lx_similarity_score'], title=title)
# print(metrics)

title = 'Similarity: LX VS GT'
metrics = get_distribution_metrics(
    small_testing['gt_vs_lx_similarity_score'], title=title)
# print(metrics)

Similarity: Text VS GT
Mean:	0.6843
Median:	0.6770
Std:	0.1125
Min:	0.4492
Max:	0.9112

Similarity: Text VS LX
Mean:	0.7858
Median:	0.8114
Std:	0.0794
Min:	0.4989
Max:	0.9211

Similarity: LX VS GT
Mean:	0.7571
Median:	0.7613
Std:	0.0984
Min:	0.5697
Max:	0.9289

In [7]:
""" Plotting Results """

plot_results(small_testing)