In [1]:
from Modules.evaluation import join_gt_and_our_dataframes, get_semantic_similarity_eval, get_distribution_metrics, evaluate_solution_df
from Modules.plotting_charts import plot_results

In [2]:
""" Constants """

GT_DF_PATH = 'Datasets/jsonllm/balanced_datasets_merge.parquet'
LX_DF_PATH = 'Datasets/lx_jsonllm/lx_jsonllm.parquet'

# Loading Datasets
MERGED_DF = join_gt_and_our_dataframes(GT_DF_PATH, LX_DF_PATH)
eval_df = MERGED_DF[:10].copy()  # For quick testing purposes

In [ ]:
""" Computing Similarities """

# new_run_full_evaluation(merged_df)
eval_df = get_semantic_similarity_eval(eval_df)
# eval_df

Embeddings (TEXT): 100%|██████████| 1/1 [00:18<00:00, 18.47s/it]
Embeddings (GT JSON): 100%|██████████| 1/1 [00:00<00:00,  1.06it/s]
Embeddings (LX JSON): 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]

,unique_id,dataset,text,gt_json_answer,lx_json_answer,text_vs_gt_similarity_score,text_vs_lx_similarity_score,gt_vs_lx_similarity_score
0,1534,mave,"""A searing, thrilling, intelligent and often b...","{""Type"": ""fiction""}","{""author"": ""John Connolly"", ""title"": ""The Blac...",0.552914,0.891223,0.669711
1,1764,mave,"""Actually, this IS my first rodeo"" Outfit your...","{""Style"": ""bodysuit""}","{""brand"": null, ""category"": ""roupa de equitaçã...",0.632537,0.656277,0.699425
2,3416,mave,"""From a darkly humorous tale of the power of w...","{""Type"": ""fiction""}","{""author"": ""Jerry Friesner, Timothy Zahn, and ...",0.570173,0.825061,0.678833
4,4270,mave,"""In a debut novel that will appeal to fans of ...","{""Fiction Form"": ""novel""}","{""genre"": ""history"", ""author"": ""McDonald""}",0.535603,0.720675,0.605515
5,4361,mave,"""In this uproarious new memoir, a New York-rai...","{""Fiction Form"": ""short-story""}","{""author"": ""Keenan"", ""category"": ""Memoir"", ""ge...",0.474370,0.745946,0.638407
6,4547,mave,"""Janicker presents students, academics, and ge...","{""Type"": ""fiction""}","{""author"": ""Janicker"", ""category"": ""livro"", ""i...",0.541145,0.877252,0.663996
7,5561,mave,"""PROPERTY OF NAVY SEALS"" yellow distressed log...","{""Sleeve Style"": ""short sleeve""}","{""brand"": null, ""category"": ""camiseta"", ""color...",0.633004,0.714722,0.768866
8,8019,mave,"""With seasoned characters, plenty of humor, an...","{""Type"": ""Fiction""}","{""author"": ""Chase"", ""category"": ""romance"", ""ge...",0.482775,0.754732,0.640362
9,8390,ae-110k,# C4 Violin 4/4 Strad 1716 hand made violin,"{""Size"": ""4/4"", ""Model Number"": ""Strad 1716""}","{""brand"": ""Strad"", ""category"": ""violino"", ""siz...",0.723931,0.840128,0.810698
10,8569,mave,#1 Selling Ladder Standoff in North America,"{""Ladder Accessory Type"": ""Ladder Standoff""}","{""brand"": null, ""category"": ""Ladder Stands"", ""...",0.764179,0.498947,0.709386

In [4]:
""" Computing Golden Evaluation Metrics """

eval_df = evaluate_solution_df(eval_df)

In [5]:
""" Printing Metrics """

# title = 'Similarity: Text VS GT'
# metrics = get_distribution_metrics(
#     eval_df['text_vs_gt_similarity_score'], title=title)
# # print(metrics)

# title = 'Similarity: Text VS LX'
# metrics = get_distribution_metrics(
#     eval_df['text_vs_lx_similarity_score'], title=title)
# # print(metrics)

# title = 'Similarity: LX VS GT'
# metrics = get_distribution_metrics(
#     eval_df['gt_vs_lx_similarity_score'], title=title)
# print(metrics)

' Printing Metrics '

In [6]:
""" Plotting Results """

# plot_results(small_testing)

' Plotting Results '

In [7]:
evaluation_dataframe_path = 'Datasets/jsonllm/jsonllm_evaluation_metrics.parquet'

eval_df.to_parquet(evaluation_dataframe_path)

In [11]:
""" Loading evaluation parquet """
import pandas as pd

evaluated_df = pd.read_parquet(evaluation_dataframe_path)
evaluated_df

,unique_id,dataset,text,gt_json_answer,lx_json_answer,text_vs_gt_similarity_score,text_vs_lx_similarity_score,gt_vs_lx_similarity_score,VN,NV,VC,VW,NN,precision,recall,f1
0,1534,mave,"""A searing, thrilling, intelligent and often b...","{""Type"": ""fiction""}","{""author"": ""John Connolly"", ""title"": ""The Blac...",0.552914,0.891223,0.669711,4,1,0,0,0,0.0,0.0,0.0
1,1764,mave,"""Actually, this IS my first rodeo"" Outfit your...","{""Style"": ""bodysuit""}","{""brand"": null, ""category"": ""roupa de equitaçã...",0.632537,0.656277,0.699425,5,1,0,0,1,0.0,0.0,0.0
2,3416,mave,"""From a darkly humorous tale of the power of w...","{""Type"": ""fiction""}","{""author"": ""Jerry Friesner, Timothy Zahn, and ...",0.570173,0.825061,0.678833,5,1,0,0,0,0.0,0.0,0.0
4,4270,mave,"""In a debut novel that will appeal to fans of ...","{""Fiction Form"": ""novel""}","{""genre"": ""history"", ""author"": ""McDonald""}",0.535603,0.720675,0.605515,2,1,0,0,0,0.0,0.0,0.0
5,4361,mave,"""In this uproarious new memoir, a New York-rai...","{""Fiction Form"": ""short-story""}","{""author"": ""Keenan"", ""category"": ""Memoir"", ""ge...",0.474370,0.745946,0.638407,4,1,0,0,0,0.0,0.0,0.0
6,4547,mave,"""Janicker presents students, academics, and ge...","{""Type"": ""fiction""}","{""author"": ""Janicker"", ""category"": ""livro"", ""i...",0.541145,0.877252,0.663996,5,1,0,0,0,0.0,0.0,0.0
7,5561,mave,"""PROPERTY OF NAVY SEALS"" yellow distressed log...","{""Sleeve Style"": ""short sleeve""}","{""brand"": null, ""category"": ""camiseta"", ""color...",0.633004,0.714722,0.768866,5,1,0,0,1,0.0,0.0,0.0
8,8019,mave,"""With seasoned characters, plenty of humor, an...","{""Type"": ""Fiction""}","{""author"": ""Chase"", ""category"": ""romance"", ""ge...",0.482775,0.754732,0.640362,5,1,0,0,0,0.0,0.0,0.0
9,8390,ae-110k,# C4 Violin 4/4 Strad 1716 hand made violin,"{""Size"": ""4/4"", ""Model Number"": ""Strad 1716""}","{""brand"": ""Strad"", ""category"": ""violino"", ""siz...",0.723931,0.840128,0.810698,5,2,0,0,0,0.0,0.0,0.0
10,8569,mave,#1 Selling Ladder Standoff in North America,"{""Ladder Accessory Type"": ""Ladder Standoff""}","{""brand"": null, ""category"": ""Ladder Stands"", ""...",0.764179,0.498947,0.709386,1,1,0,0,4,0.0,0.0,0.0